# Generated by Django 6.0.6 on 2026-06-10 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('attendance', models.FloatField()),
                ('internal_marks', models.FloatField()),
                ('assignment_score', models.FloatField()),
                ('study_hours', models.FloatField()),
                ('gpa', models.FloatField()),
            ],
        ),
    ]
