# Generated by Django 6.0.6 on 2026-06-18 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predictor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='predicted_score',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
