# Generated by Django 6.0.6 on 2026-06-19 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('predictor', '0002_student_predicted_score'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='gpa',
            new_name='internal_test_1',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='internal_marks',
            new_name='internal_test_2',
        ),
    ]
