# Generated by Django 6.0.6 on 2026-06-19 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predictor', '0003_rename_gpa_student_internal_test_1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='suggestion',
            field=models.TextField(blank=True),
        ),
    ]
